#!/bin/bash

SOURCE=$1
LFN=$2

if [ -L $LFN ]; then
    echo "$LFN already exists as an LFN"
    exit 1
fi

if [ "${LFN:0:7}" != "/store/" ]; then
    echo "LFN must start from /store/"
    exit 1
fi

LFDIR=$(dirname $LFN)

if [ -e $LFDIR -a ! -d $LFDIR ]; then
    echo "$LFDIR already exists and is not a directory"
    exit 1
fi

if [ ! -e $LFDIR ]; then
    SUPERDIR=$LFDIR
    while [ ! -e $SUPERDIR ]; do
        THISDIR=$SUPERDIR
        SUPERDIR=$(dirname $SUPERDIR)
    done
    mkdir -p $LFDIR
    chmod -R g+w $THISDIR
fi

# use the least occupied disk
DISK=$(df | awk 'BEGIN {min=-1; disk=""}; /disk[0-9]*/ {if(min < 0 || min > $3){min = $3; disk=$6; sub(/\/data\//, "", disk);}}; END {print disk}')

PFN=/data/${DISK}/${LFN:7}

PFDIR=$(dirname $PFN)

if [ -e $PFDIR -a ! -d $PFDIR ]; then
    echo "Destination is not a directory"
    exit 1
fi

if [ ! -e $PFDIR ]; then
    SUPERDIR=$PFDIR
    while [ ! -e $SUPERDIR ]; do
        THISDIR=$SUPERDIR
        SUPERDIR=$(dirname $SUPERDIR)
    done
    mkdir -p $PFDIR
    chmod -R g+w $THISDIR
fi

cmsStage $SOURCE $PFN && ln -s $PFN $LFN

exit $?
